import { Inter } from 'next/font/google'
import Navbar from '@/components/layout/Navbar'
import Head from 'next/head'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <>
      {/* <Head> */}
      <title>Sondype</title>
      {/* </Head> */}

      <Navbar />
      <main>{children}</main>
    </>
  )
}
